FileVersion = 1
Dependencies = {corlib = "*", Raylib = "*", corlib = "*"}

[Project]
Name = "BasicWindow"
StartupObject = "Raylib.Examples.BasicWindow.Program"
DefaultNamespace = "Raylib.Examples.BasicWindow"
