FileVersion = 1
Dependencies = {corlib = "*", corlib = "*", corlib = "*"}

[Project]
Name = "raylib-beef"
TargetType = "BeefLib"
StartupObject = "Program"

[Configs.DebugStatic.Win64]
OtherLinkFlags = "$(LinkFlags) -libpath:\"$(ProjectDir)/dist/win64/\""
LibPaths = ["$(ProjectDir)/dist/win64/raylib.lib"]

[Configs.DebugStatic.Win32]
OtherLinkFlags = "$(LinkFlags) $(LinkFlags) -libpath:\"$(ProjectDir)/dist/win32/\""
LibPaths = ["$(ProjectDir)/dist/win32/raylib.lib"]

[Configs.ReleaseStatic.Win64]
OtherLinkFlags = "$(LinkFlags) -libpath:\"$(ProjectDir)/dist/win64/\""
LibPaths = ["$(ProjectDir)/dist/win64/raylib.lib"]

[Configs.ReleaseStatic.Win32]
OtherLinkFlags = "$(LinkFlags) $(LinkFlags) -libpath:\"$(ProjectDir)/dist/win32/\""
LibPaths = ["$(ProjectDir)/dist/win32/raylib.lib"]

[Configs.Release.Win64]
OtherLinkFlags = "$(LinkFlags) -libpath:\"$(ProjectDir)/dist/win64/\""
LibPaths = ["$(ProjectDir)/dist/win64/raylibdll.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/win64/*.dll\")"]

[Configs.Release.Win32]
OtherLinkFlags = "$(LinkFlags) $(LinkFlags) -libpath:\"$(ProjectDir)/dist/win32/\""
LibPaths = ["$(ProjectDir)/dist/win32/raylibdll.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/win32/*.dll\")"]

[Configs.Debug.Win64]
OtherLinkFlags = "$(LinkFlags) -libpath:\"$(ProjectDir)/dist/win64/\""
LibPaths = ["$(ProjectDir)/dist/win64/raylibdll.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/win64/*.dll\")"]

[Configs.Debug.Win32]
OtherLinkFlags = "$(LinkFlags) $(LinkFlags) -libpath:\"$(ProjectDir)/dist/win32/\""
LibPaths = ["$(ProjectDir)/dist/win32/raylibdll.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/win32/*.dll\")"]

[Configs.Debug.wasm32]
LibPaths = ["$(ProjectDir)/dist/wasm32/libraylib.a"]
