FileVersion = 1
Projects = {Raylib = {Path = "."}, BasicWindow = {Path = "examples/core/basic"}}
WorkspaceFolders = {Examples = [], "Examples/Core" = ["BasicWindow"]}

[Workspace]
StartupProject = "BasicWindow"

[Configs.Debug.wasm32]
AllocType = "CRT"
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false

[Configs.Test.wasm32]
AllocType = "CRT"
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false
