FileVersion = 1
Projects = {Raylib = {Path = "."}, BasicWindow = {Path = "examples/core/basic"}, InputKeys = {Path = "examples/core/input_keys"}, BasicWindowWeb = {Path = "examples/core/basic_window_web"}}
WorkspaceFolders = {Examples = [], "Examples/Core" = ["BasicWindow", "InputKeys", "BasicWindowWeb"]}

[Workspace]
StartupProject = "BasicWindowWeb"

[Configs.Debug.wasm32]
AllocType = "CRT"
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false

[Configs.Test.wasm32]
AllocType = "CRT"
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false
