FileVersion = 1
Projects = {Raylib = {Path = "."}, BasicWindow = {Path = "examples/core/basic"}, InputKeys = {Path = "examples/core/input_keys"}, BasicWindowWeb = {Path = "examples/core/basic_window_web"}, RaylibApp = {Path = "examples/extensions/RaylibApp"}}
WorkspaceFolders = {Examples = [], "Examples/Core" = ["BasicWindow", "InputKeys", "BasicWindowWeb"], "Examples/Extensions" = ["RaylibApp"]}

[Workspace]
StartupProject = "RaylibApp"

[Configs.Debug.wasm32]
AllocType = "CRT"
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false

[Configs.Test.wasm32]
AllocType = "CRT"
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false
