FileVersion = 1
Projects = {Raylib = {Path = "."}, Basic = {Path = "examples/basic"}}
WorkspaceFolders = {Examples = ["Basic"]}

[Workspace]
StartupProject = "Basic"

[Configs.Debug.wasm32]
AllocType = "CRT"
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false

[Configs.Test.wasm32]
AllocType = "CRT"
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false
