FileVersion = 1
Dependencies = {corlib = "*", corlib = "*", corlib = "*"}

[Project]
Name = "Raylib"
TargetType = "BeefLib"
StartupObject = "Program"

[Configs.Test.Win64]
OtherLinkFlags = "$(LinkFlags) -libpath:\"$(ProjectDir)/dist/win64/\""
LibPaths = ["$(ProjectDir)/dist/win64/raylib.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/win64/*.dll\")"]

[Configs.Test.Win32]
OtherLinkFlags = "$(LinkFlags) -libpath:\"$(ProjectDir)/dist/win32/\""
LibPaths = ["$(ProjectDir)/dist/win32/raylib.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/win32/*.dll\")"]

[Configs.Release.Win64]
OtherLinkFlags = "$(LinkFlags) -libpath:\"$(ProjectDir)/dist/win64/\""
LibPaths = ["$(ProjectDir)/dist/win64/raylib.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/win64/*.dll\")"]

[Configs.Release.Win32]
OtherLinkFlags = "$(LinkFlags) -libpath:\"$(ProjectDir)/dist/win32/\""
LibPaths = ["$(ProjectDir)/dist/win32/raylib.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/win32/*.dll\")"]

[Configs.Release.wasm32]
OtherLinkFlags = "$(LinkFlags) -g -s USE_GLFW=3 -s ASYNCIFY -s ALLOW_MEMORY_GROWTH=1"
LibPaths = ["$(ProjectDir)/dist/wasm32/libraylib.a"]

[Configs.Debug.Win64]
OtherLinkFlags = "$(LinkFlags) -libpath:\"$(ProjectDir)/dist/win64/\""
LibPaths = ["$(ProjectDir)/dist/win64/raylib.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/win64/*.dll\")"]

[Configs.Debug.Win32]
OtherLinkFlags = "$(LinkFlags) -libpath:\"$(ProjectDir)/dist/win32/\""
LibPaths = ["$(ProjectDir)/dist/win32/raylib.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/win32/*.dll\")"]

[Configs.Debug.wasm32]
OtherLinkFlags = "$(LinkFlags) -g -s USE_GLFW=3 --use-preload-plugins -s ALLOW_MEMORY_GROWTH=1 -s ASSERTIONS=1 -s SAFE_HEAP=0 -s DETERMINISTIC=1 -s ASYNCIFY"
LibPaths = ["$(ProjectDir)/dist/wasm32/libraylib.a"]
